### ISSUE TITLE
Author is not reachable for reporting of Arch Linux repository problems: "mailbox unavailable".

### ISSUE THREAD

**Issue by felixbecker2** [maximbaz/pkgbuilds#13]
I wanted to send [maximbaz](https://github.com/maximbaz/) an email about a problem with his Arch Linux repository "maximbaz".

However, the Email address `archlinux at maximbaz dot com` noted at
https://www.archlinux.org/people/trusted-users/#maximbaz does not work:

    (host mail.gmx.net[212.227.17.190] said: 550-Requested action not taken: mailbox unavailable 550 invalid DNS MX or A/AAAA resource record (in reply to RCPT TO command))

Further Emails I could find out (`git at` (as they are mentioned in commit comments), `pgp at` (as it is mentioned in the OpenPGP key available at https://maximbaz.com/pgp_keys.asc)) do not work with the same reason.

This is to inform you about this. (The problem with the repository
seems to be fixed by now).

Regards!

**Comment by maximbaz** [comment]
Thanks for letting me know! The email address is definitely valid, I'll be checking the backend systems. Repo was fixed yesterday, someone else has also pinged me :slightly_smiling_face: Sorry for the trouble!

**Comment by maximbaz** [comment]
I have identified and fixed the issue in my DNS setup, would you be so kind to send me a test email to any of those addresses?

**Comment by felixbecker2** [comment]
On Thu, 30 Jan 2020 04:36:29 -0800, Maxim Baz
<notifications@github.com> wrote about "Re: [maximbaz/pkgbuilds] Author
is not reachable for reporting of Arch Linux repository problems:
"mailbox unavailable". (#13)":

> I have identified and fixed the issue in my DNS setup, would you be
> so kind to send me a test email to any of those addresses?

I just re-flused my mail queue, the old emails where still in there.
Treat them as the test-messages ;).

Thanks for fixing it.

Regards,
Felix Becker.
