### ISSUE TITLE
wl-clipboard-manager repo has been deleted

### ISSUE THREAD

**Issue by gi-yt** [maximbaz/pkgbuilds#16]

**Comment by maximbaz** [comment]
Thanks, I removed it from here as well. The package is obsolete, it has been too specific to my own setup, so I merged it into my own dotfiles repo.

**Comment by gi-yt** [comment]
oh i use wl-clipboard-manager on a daily basis so was surprised that it disappeared

**Comment by maximbaz** [comment]
oh I didn't know anyone used it 🙂 have you modified it at all, or dmenu-term?

**Comment by gi-yt** [comment]
no i just used it stock lol
